# Generated by Django 5.0.6 on 2024-07-02 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('opening_hours', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('restaurant_style', models.CharField(choices=[('Indian', 'Indian'), ('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Chinese', 'Chinese'), ('Indian, North Indian, Chinese', 'Indian, North Indian, Chinese'), ('Asian', 'Asian'), ('Italian', 'Italian'), ('French', 'French'), ('American', 'American'), ('Mexican', 'Mexican'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Thai', 'Thai'), ('Mediterranean', 'Mediterranean'), ('Middle Eastern', 'Middle Eastern'), ('Greek', 'Greek'), ('Spanish', 'Spanish'), ('Korean', 'Korean'), ('Vietnamese', 'Vietnamese'), ('German', 'German'), ('Caribbean', 'Caribbean'), ('African', 'African'), ('Seafood', 'Seafood'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan')], max_length=50)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='Restaurant_baner_image/')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_images/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webvoid.restaurant')),
            ],
        ),
    ]
