# Generated by Django 5.0.6 on 2024-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webvoid', '0002_remove_menu_additional_images_menureview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('raised_to', models.CharField(choices=[('server', 'Server'), ('food', 'Food'), ('management', 'Hotel Management'), ('cleanliness', 'Cleanliness'), ('ambiance', 'Ambiance'), ('billing', 'Billing'), ('service_speed', 'Service Speed'), ('other', 'Other')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='complaint_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
